#+TITLE: dotnet fundamentals
#+Author: ggmon
#+STARTUP: overview
#+STARTUP: hidestars


* Refreneces

  http://en.wikipedia.org/wiki/.NET_Framework


* Dot Net Framework

  Includes a large library of pre-coded solutions to common problems
  written specifically for the framework.The pre-coded solutions that
  form the framework's Base Class Library cover a large range of
  programming needs in a number of areas, including user interface,
  data access, database connectivity, cryptography, web application
  development, numeric algorithms, and network communications. The
  class library is used by programmers, who combine it with their own
  code to produce applications.

  The programs written for .NET framework execute in a software
  environment that manages the program's runtime requirements. this
  runtime environment is known as the Common Language Runtime
  (CLR). The CLR provides the appearance of an application virtual
  machine so that the programmers need not considet the capabilities
  of the specific CPU tha will execute the program.

  The CLR provides the important services such as security, memory
  management and exception handling. The class Library and the CLR
  together composes the .NET Framework.

    
** Principle design features
   
*** Interoperability

*** Common Runtime  Engine

*** Base Class Library
    The Base Class Library (BCL), part of the Framework Class Library
    (FCL), is a library of functionality available to all languages
    using the .NET Framework. The BCL provides classes which
    encapsulate a number of common functions, including file reading
    and writing, graphic rendering, database interaction and XML
    document manipulation.

    
*** Simplified depolyment

*** Scurity

*** Portablity



** Architecture


*** Common Language Infrastrucutue [[file:cli.org][link]]
    
    The core aspects of the .NET framework lie within the Common
    Language Infrastructure, or CLI. The purpose of the CLI is to
    provide a language-neutral platform for application development
    and execution, including functions for exception handling, garbage
    collection, security, and interoperability. Microsoft's
    implementation of the CLI is called the Common Language Runtime or
    CLR.

*** Assemblies

    The Intermediate common intermediate language(CIL) code is housed
    in .NET assemblies. As mandated by specification, assemblies are
    stored in the Portable Executable(PE) format, common on windows
    platforms for all DLL and EXE files. The assembly consits of one
    or more files, one of which must contain the manifest, which has
    the metadata for the assembly. The complete name of an assembly
    contains its simple text name, version number, culture and public
    key token. The public key is a unique hash which is generated when
    the assembly is compiled.thus two assemblies with the same public
    key token are guaranteed to be identical from the point of view of
    the framework. A private key can also be specified known only to
    the creator of the assembly and can be used for strong naming and
    to guarantee that the assembly is from the same author.


*** MetaData

    ALL CLI is self-describing through .NET metadata. The CLR checks
    the metadata to ensure that the correct method is called. Metadata
    is usually generated by the language compilers, but developers can
    develop their own metadata through custom attributes.Meta data
    contain information about the assembly, and is also used for
    reflective programming on .NET

*** Security

    .NET has its own security mechanism with two general features:
    Code Access Security(CAS), and validation and verification.


*** Class Library 
    

    

    
    




    

   


